spring.application.name=guias-despacho
server.port=8080

app.efs.path=${EFS_PATH:/app/efs}

aws.s3.bucket=${S3_BUCKET:guias-despacho-bucket}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.software.amazon.awssdk=INFO
logging.level.io.awspring.cloud=INFO

app.security.enabled=${SECURITY_ENABLED:false}
app.security.jwks-uri=${B2C_JWKS_URI:https://icgrupo5.b2clogin.com/icgrupo5.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_descargas}
app.security.issuers=${B2C_ISSUERS:https://icgrupo5.b2clogin.com/tfp/7570a3ed-2cc2-471f-9c9b-f6d7384d0ba6/b2c_1_gestor/v2.0/,https://icgrupo5.b2clogin.com/tfp/7570a3ed-2cc2-471f-9c9b-f6d7384d0ba6/b2c_1_descargas/v2.0/}
app.security.roles-claim=${B2C_ROLES_CLAIM:extension_Role}
app.security.role-descarga=${ROLE_DESCARGA:descargas}
app.security.role-gestor=${ROLE_GESTOR:gestor}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.default-requeue-rejected=false

app.rabbitmq.guias.queue=resumen.guias.queue
app.rabbitmq.guias.exchange=resumen.guias.exchange
app.rabbitmq.guias.routing-key=resumen.guias.routingkey
app.rabbitmq.guias.dlq=resumen.guias.dlq
app.rabbitmq.guias.dlx=resumen.guias.dlx
app.rabbitmq.guias.dlq-routing-key=resumen.guias.dlq.routingkey

spring.datasource.url=jdbc:h2:mem:guiasdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Comentario para ultimo commit