spring.application.name=guias-despacho
server.port=8080

app.efs.path=${EFS_PATH:/app/efs}

aws.s3.bucket=${S3_BUCKET:guias-despacho-bucket}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.software.amazon.awssdk=INFO
logging.level.io.awspring.cloud=INFO

app.security.enabled=${SECURITY_ENABLED:false}
app.security.jwks-uri=${B2C_JWKS_URI:https://icgrupo5.b2clogin.com/icgrupo5.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_descargas}
app.security.issuers=${B2C_ISSUERS:https://icgrupo5.b2clogin.com/tfp/7570a3ed-2cc2-471f-9c9b-f6d7384d0ba6/b2c_1_gestor/v2.0/,https://icgrupo5.b2clogin.com/tfp/7570a3ed-2cc2-471f-9c9b-f6d7384d0ba6/b2c_1_descargas/v2.0/}
app.security.roles-claim=${B2C_ROLES_CLAIM:extension_Role}
app.security.role-descarga=${ROLE_DESCARGA:descargas}
app.security.role-gestor=${ROLE_GESTOR:gestor}

# prueba de Deployment final
